[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "browsergym-medgym"
description = "Medical GUI CUA Benchmark for BrowserGym"
authors = [
    {name = "MedGym Team"},
]
readme = "README.md"
requires-python = ">3.9"
license = {text = "Apache-2.0"}
version = "0.1.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dynamic = ["dependencies"]

[project.urls]
homepage = "https://github.com/Jia7878/MedCUA-BenchMark"
repository = "https://github.com/Jia7878/MedCUA-BenchMark"

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[tool.hatch.build.targets.wheel]
packages = ["src/browsergym"]
